// <auto-generated />
using DNSPromotionManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DNSPromotionManager.Migrations
{
    [DbContext(typeof(DNSContext))]
    [Migration("20180319102743_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DNSPromotionManager.Models.KindProduct", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Code")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Kinds");
                });

            modelBuilder.Entity("DNSPromotionManager.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Code")
                        .HasMaxLength(10);

                    b.Property<bool>("DelFlag");

                    b.Property<string>("KindId");

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.Property<string>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("KindId");

                    b.HasIndex("ParentId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DNSPromotionManager.Models.Product", b =>
                {
                    b.HasOne("DNSPromotionManager.Models.KindProduct", "Kind")
                        .WithMany()
                        .HasForeignKey("KindId");

                    b.HasOne("DNSPromotionManager.Models.Product", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
